type: "transformation"
version: "1.0"
pipeline:
  metadata:
    description: "Load new CALL_PRIORITY records from LOOKUP into DIM_CALL_PRIORITY\
      \ incrementally"
    origin: "maia-019f1e2b-9c63-7ec7-bb00-45ed227c9910"
  components:
    Input Lookup:
      type: "table-input"
      parameters:
        componentName: "Input Lookup"
        database: "[Environment Default]"
        schema: "EXTRACT"
        targetTable: "LOOKUP"
        columnNames:
        - "LOOKUP_FILTER"
        - "LOOKUP_CODE"
        - "LOOKUP_SHORT_NAME"
        - "LOOKUP_DESC"
        - "LOOKUP_SORT_ORDER"
    Filter Call Priority:
      type: "filter"
      sources:
      - "Input Lookup"
      parameters:
        componentName: "Filter Call Priority"
        filterConditions:
        - - "LOOKUP_FILTER"
          - "Is"
          - "Equal to"
          - "CALL_PRIORITY"
        combineCondition: "And"
    Calculate Uppercase:
      type: "calculator"
      sources:
      - "Filter Call Priority"
      parameters:
        componentName: "Calculate Uppercase"
        includeInputColumns: "Yes"
        calculations:
        - - |
            UPPER("LOOKUP_CODE")
          - "CALL_PRIORITY_CODE"
        - - |
            UPPER("LOOKUP_SHORT_NAME")
          - "CALL_PRIORITY"
        - - |
            UPPER("LOOKUP_DESC")
          - "CALL_PRIORITY_DESC"
    Filter New Records:
      type: "sql"
      sources:
      - "Calculate Uppercase"
      parameters:
        componentName: "Filter New Records"
        query: |
          SELECT "CALL_PRIORITY_CODE", "CALL_PRIORITY", "CALL_PRIORITY_DESC", "LOOKUP_SORT_ORDER" AS "CALL_PRIORITY_SORT_ORDER"
          FROM $T{Calculate Uppercase}
          WHERE "CALL_PRIORITY_CODE" NOT IN (
            SELECT "CALL_PRIORITY_CODE"
            FROM "CALL_CENTER_ANALYTICS_DW"."DWH"."DIM_CALL_PRIORITY"
          )
    Insert DIM_CALL_PRIORITY:
      type: "table-output"
      sources:
      - "Filter New Records"
      parameters:
        componentName: "Insert DIM_CALL_PRIORITY"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "DWH"
        targetTable: "DIM_CALL_PRIORITY"
        fixDataTypeMismatches: "Yes"
        columnMapping:
        - - "CALL_PRIORITY_CODE"
          - "CALL_PRIORITY_CODE"
        - - "CALL_PRIORITY"
          - "CALL_PRIORITY"
        - - "CALL_PRIORITY_DESC"
          - "CALL_PRIORITY_DESC"
        - - "CALL_PRIORITY_SORT_ORDER"
          - "CALL_PRIORITY_SORT_ORDER"
        outputMode: "Append"
design:
  components:
    Input Lookup:
      position:
        x: 0
        "y": 0
      tempMetlId:
    Filter Call Priority:
      position:
        x: 160
        "y": 0
      tempMetlId:
    Calculate Uppercase:
      position:
        x: 320
        "y": 0
      tempMetlId:
    Filter New Records:
      position:
        x: 480
        "y": 0
      tempMetlId:
    Insert DIM_CALL_PRIORITY:
      position:
        x: 640
        "y": 0
      tempMetlId:
